# COMP90024 Team 2

# Background weather ingestion: manual or timer-triggered.
# NOT used by the frontend notebook.
apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  name: route-harvest-weather
  namespace: default
spec:
  host: ""
  relativeurl: /ingest/harvest-weather
  method: POST
  functionref:
    type: name
    name: harvest-weather
